// ローカルの `astro dev`（Go 関数なし）でもトップページが動くようにするための
// フォールバック。値は Go スコアラーの実出力を書き写したもの。
// Vercel 上では /api/resources（Go）が本物のレスポンスを返す。
import type { ResourcesResponse } from './types';

export const SAMPLE_RESPONSE: ResourcesResponse = {
  source: 'sample',
  query: 'tag:Go',
  count: 6,
  total: 6,
  weights: {
    tag: 0.22,
    prerequisite: 0.2,
    jargon: 0.2,
    explanatoriness: 0.1,
    externalRefs: 0.13,
    codeRatio: 0.12,
    length: 0.03,
  },
  thresholds: { Intermediate: 1.8, Advanced: 3.2 },
  resources: [
    {
      title: 'Goスケジューラ(GMPモデル)の内部実装とプリエンプション',
      url: 'https://qiita.com/example/items/go-scheduler-internals',
      source: 'Qiita',
      author: 'runtime_hacker',
      likes: 355,
      publishedAt: '2025-04-01T10:00:00+09:00',
      tags: ['Go', '内部実装', 'golang-internal', '並行処理'],
      summary:
        '本記事では goroutine と channel の基礎は理解している前提で、Go ランタイムのスケジューラを解説します',
      difficulty: 3.87,
      level: 'advanced',
      levelLabel: '上級',
      topics: { go: 3.87 },
      signals: [
        { name: 'tag', raw: '+内部実装 +並行処理', value: 1, weight: 0.22, contribution: 1.03 },
        { name: 'prerequisite', raw: '1 箇所で前提知識に言及', value: 0.6, weight: 0.2, contribution: 0.56 },
        { name: 'jargon', raw: '11 種の専門用語', value: 1, weight: 0.2, contribution: 0.93 },
        { name: 'explanatoriness', raw: '0 見出し / 0 図', value: 0, weight: -0.1, contribution: 0 },
        { name: 'externalRefs', raw: '2 件の一次資料リンク (RFC/論文/仕様)', value: 0.67, weight: 0.13, contribution: 0.4 },
        { name: 'codeRatio', raw: '3% がコード', value: 0.08, weight: 0.12, contribution: 0.04 },
        { name: 'length', raw: '620 文字', value: 0.2, weight: 0.03, contribution: 0.03 },
      ],
    },
    {
      title: 'Goのcontextパッケージを正しく理解する',
      url: 'https://qiita.com/example/items/go-context-deep',
      source: 'Qiita',
      author: 'concurrent_ken',
      likes: 210,
      publishedAt: '2025-05-20T18:00:00+09:00',
      tags: ['Go', '並行処理'],
      summary: 'goroutine のキャンセル伝播とタイムアウト制御には context を使います',
      difficulty: 3.36,
      level: 'advanced',
      levelLabel: '上級',
      topics: { go: 3.36 },
      signals: [
        { name: 'tag', raw: '+並行処理', value: 0.75, weight: 0.22, contribution: 0.77 },
        { name: 'prerequisite', raw: '1 箇所で前提知識に言及', value: 0.6, weight: 0.2, contribution: 0.56 },
        { name: 'jargon', raw: '7 種の専門用語', value: 0.74, weight: 0.2, contribution: 0.68 },
        { name: 'explanatoriness', raw: '0 見出し / 0 図', value: 0, weight: -0.1, contribution: 0 },
        { name: 'externalRefs', raw: '1 件の一次資料リンク (RFC/論文/仕様)', value: 0.33, weight: 0.13, contribution: 0.2 },
        { name: 'codeRatio', raw: '11% がコード', value: 0.28, weight: 0.12, contribution: 0.15 },
        { name: 'length', raw: '400 文字', value: 0.13, weight: 0.03, contribution: 0.02 },
      ],
    },
    {
      title: 'PostgreSQLのインデックスとクエリプランを読む',
      url: 'https://qiita.com/example/items/pg-index-explain',
      source: 'Qiita',
      author: 'db_specialist',
      likes: 176,
      publishedAt: '2025-06-25T15:00:00+09:00',
      tags: ['PostgreSQL', 'SQL', 'アーキテクチャ'],
      summary: 'EXPLAIN ANALYZE の読み方と B-tree インデックスの効き方を解説します',
      difficulty: 2.51,
      level: 'intermediate',
      levelLabel: '中級',
      topics: { sql: 2.51 },
      signals: [
        { name: 'tag', raw: '+アーキテクチャ', value: 0.75, weight: 0.22, contribution: 0.77 },
        { name: 'prerequisite', raw: '1 箇所で前提知識に言及', value: 0.6, weight: 0.2, contribution: 0.56 },
        { name: 'jargon', raw: '4 種の専門用語', value: 0.42, weight: 0.2, contribution: 0.38 },
        { name: 'explanatoriness', raw: '0 見出し / 0 図', value: 0, weight: -0.1, contribution: 0 },
        { name: 'externalRefs', raw: '0 件の一次資料リンク (RFC/論文/仕様)', value: 0, weight: 0.13, contribution: 0 },
        { name: 'codeRatio', raw: '9% がコード', value: 0.23, weight: 0.12, contribution: 0.12 },
        { name: 'length', raw: '360 文字', value: 0.1, weight: 0.03, contribution: 0.01 },
      ],
    },
    {
      title: 'Goのスライスとマップを実務で使い分ける',
      url: 'https://qiita.com/example/items/go-slice-map',
      source: 'Qiita',
      author: 'gopher_hanako',
      likes: 88,
      publishedAt: '2025-07-02T12:30:00+09:00',
      tags: ['Go', '備忘録'],
      summary: '業務コードでよく出てくるスライスとマップの扱いを整理します',
      difficulty: 0.84,
      level: 'beginner',
      levelLabel: '初級',
      topics: { go: 0.84 },
      signals: [
        { name: 'tag', raw: '−備忘録', value: 0.25, weight: 0.22, contribution: 0.26 },
        { name: 'prerequisite', raw: '0 箇所で前提知識に言及', value: 0, weight: 0.2, contribution: 0 },
        { name: 'jargon', raw: '2 種の専門用語', value: 0.21, weight: 0.2, contribution: 0.19 },
        { name: 'explanatoriness', raw: '2 見出し / 0 図', value: 0.17, weight: -0.1, contribution: -0.08 },
        { name: 'externalRefs', raw: '0 件の一次資料リンク (RFC/論文/仕様)', value: 0, weight: 0.13, contribution: 0 },
        { name: 'codeRatio', raw: '13% がコード', value: 0.33, weight: 0.12, contribution: 0.18 },
        { name: 'length', raw: '340 文字', value: 0.09, weight: 0.03, contribution: 0.01 },
      ],
    },
    {
      title: 'Docker Composeで開発環境を作る最小構成',
      url: 'https://qiita.com/example/items/docker-compose-minimal',
      source: 'Qiita',
      author: 'infra_beginner',
      likes: 64,
      publishedAt: '2025-07-18T11:00:00+09:00',
      tags: ['Docker', 'docker-compose', '初心者'],
      summary: 'Docker Compose 入門 はじめて Docker Compose を触る人向けに、Web アプリと DB の 2 サービス構成を作ります',
      difficulty: 0.79,
      level: 'beginner',
      levelLabel: '初級',
      topics: { docker: 0.79 },
      signals: [
        { name: 'tag', raw: '−初心者', value: 0.25, weight: 0.22, contribution: 0.26 },
        { name: 'prerequisite', raw: '0 箇所で前提知識に言及', value: 0, weight: 0.2, contribution: 0 },
        { name: 'jargon', raw: '0 種の専門用語', value: 0, weight: 0.2, contribution: 0 },
        { name: 'explanatoriness', raw: '3 見出し / 0 図', value: 0.25, weight: -0.1, contribution: -0.13 },
        { name: 'externalRefs', raw: '0 件の一次資料リンク (RFC/論文/仕様)', value: 0, weight: 0.13, contribution: 0 },
        { name: 'codeRatio', raw: '25% がコード', value: 0.62, weight: 0.12, contribution: 0.34 },
        { name: 'length', raw: '300 文字', value: 0.06, weight: 0.03, contribution: 0.01 },
      ],
    },
    {
      title: 'Go言語入門：Hello Worldから基本文法まで',
      url: 'https://qiita.com/example/items/beginner-go-101',
      source: 'Qiita',
      author: 'study_taro',
      likes: 42,
      publishedAt: '2025-06-10T09:00:00+09:00',
      tags: ['Go', '初心者', 'プログラミング初心者'],
      summary: 'この記事はプログラミングを始めたばかりの人向けに、Go言語の基本を丁寧に説明します',
      difficulty: 0.39,
      level: 'beginner',
      levelLabel: '初級',
      topics: { go: 0.39 },
      signals: [
        { name: 'tag', raw: '−初心者 −プログラミング初心者', value: 0, weight: 0.22, contribution: 0 },
        { name: 'prerequisite', raw: '0 箇所で前提知識に言及', value: 0, weight: 0.2, contribution: 0 },
        { name: 'jargon', raw: '0 種の専門用語', value: 0, weight: 0.2, contribution: 0 },
        { name: 'explanatoriness', raw: '4 見出し / 0 図', value: 0.33, weight: -0.1, contribution: -0.17 },
        { name: 'externalRefs', raw: '0 件の一次資料リンク (RFC/論文/仕様)', value: 0, weight: 0.13, contribution: 0 },
        { name: 'codeRatio', raw: '17% がコード', value: 0.42, weight: 0.12, contribution: 0.23 },
        { name: 'length', raw: '380 文字', value: 0.12, weight: 0.03, contribution: 0.02 },
      ],
    },
  ],
};
